```{r}
set.seed(22)
library(dplyr)
library(caret)
library(e1071)
library(rpart)
library(rpart.plot)
library(glmnet)
library(pROC)
library(FSelectorRcpp)
```

###Manually add the attribute names to the data file 

```{r}
spambase <- read.csv(url("http://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"), header = FALSE)

names(spambase) <- c("word_freq_make",
                         "word_freq_address",
                         "word_freq_all",
                         "word_freq_3d",
                         "word_freq_our",
                         "word_freq_over",
                         "word_freq_remove",
                         "word_freq_internet",
                         "word_freq_order",
                         "word_freq_mail",
                         "word_freq_receive",
                         "word_freq_will",
                         "word_freq_people",
                         "word_freq_report",
                         "word_freq_addresses",
                         "word_freq_free",
                         "word_freq_business",
                         "word_freq_email",
                         "word_freq_you",
                         "word_freq_credit",
                         "word_freq_your",
                         "word_freq_font",
                         "word_freq_000",
                         "word_freq_money",
                         "word_freq_hp",
                         "word_freq_hpl",
                         "word_freq_george",
                         "word_freq_650",
                         "word_freq_lab",
                         "word_freq_labs",
                         "word_freq_telnet",
                         "word_freq_857",
                         "word_freq_data",
                         "word_freq_415",
                         "word_freq_85",
                         "word_freq_technology",
                         "word_freq_1999",
                         "word_freq_parts",
                         "word_freq_pm",
                         "word_freq_direct",
                         "word_freq_cs",
                         "word_freq_meeting",
                         "word_freq_original",
                         "word_freq_project",
                         "word_freq_re",
                         "word_freq_edu",
                         "word_freq_table",
                         "word_freq_conference",
                         "char_freq_;",
                         "char_freq_(",
                         "char_freq_[",
                         "char_freq_!",
                         "char_freq_$",
                         "char_freq_#",
                         "capital_run_length_average",
                         "capital_run_length_longest",
                         "capital_run_length_total", 
                         "spam"
)
```


###Use 5 fold validation to evaluate the performance of the logistic regression on this dataset
###Report average Accurcy, Precision, Recall, F-measure, and AUC
```{r}
# creating cross-validation folds
cv2 <- createFolds(y = spambase$spam, k = 5)

accuracy <- c() # empty vector to store accuracy from each test fold
precision <- c() # empty vector to store Precision from each test fold
recall <- c() # empty vector to store Recall from each test fold
F1 <- c() # empty vector to store F1 from each test fold
auc <- c() # empty vector to store AUC from each test fold

for(test_fold in cv2){

  train = spambase[-test_fold, ]
  test = spambase[test_fold, ]
  
  logit_model = glm(spam ~ . , data = train, family = "binomial")
  
  pred_prob = predict(logit_model, test, type = "response")
  pred_binary = ifelse(pred_prob > .5, 1, 0)
  
  cm = confusionMatrix(factor(pred_binary), factor(test$spam), positive = "1", mode = "prec_recall")
  
  accuracy = c(accuracy, cm$overall[1])
  precision = c(precision, cm$byClass["Precision"])
  recall = c(recall, cm$byClass["Recall"])
  F1 = c(F1, cm$byClass["F1"])
  auc = c(auc,auc(test$spam, pred_prob))
}
```

###Perform feature selection using Information Gain
```{r}
aucs = c() # empty vector to store mean AUC for each set of top features

for(i in 1:(dim(spambase)[2]-1)){
  auc = c()
  
  for(test_row in cv2){
    
  train = spambase[-test_fold, ]
  test = spambase[test_fold, ]  
  
  ig = information_gain(spam ~ . , data = train)
  
  topk = cut_attrs(ig, k = i)
  
  train = train %>% select(topk, spam)
  test = test %>% select(topk, spam)
  
  logit_model_f = glm(spam ~ . , data = train, family = "binomial")
  
  pred_prob = predict(logit_model_f, test, type = "response")
  
  auc = c(auc, auc(test$spam, pred_prob))
  }
  aucs = c(aucs, mean(auc))
  }

print(max(aucs)) # best AUC
```

###Forward feature selection
```{r}
best_auc <- 0.5
selected_features <- c()

while(TRUE){

  feature_to_add <- -1

  for(i in setdiff(1:(dim(spambase)[2]-1), selected_features)){

      aucs <- c() # empty vector to store AUC from each fold

      for(test_fold in cv2){

      train <- spambase[-test_fold, ] %>% select(selected_features, i, spam)
      test <- spambase[test_fold, ] %>% select(selected_features, i, spam)

      logit_model_wf <- glm(spam ~ . , data = train, family = "binomial")

      pred_prob_wf <- predict(logit_model_wf, test, type = "response")

      aucs <- c(aucs, auc(test$spam, pred_prob_wf))
      }

      auc_wf <- mean(aucs) # mean AUC from the current set of features

      if(auc_wf > best_auc){
        best_auc <- auc_wf
        feature_to_add <- i
      }
  }

  if (feature_to_add != -1){
    selected_features <- c(selected_features, feature_to_add)
    print(selected_features) 
    print(best_auc) 
  }
  else break
}
```